// ─── Single Source of Truth for all surf spot data ──────────────────────────

export interface SpotData {
  id: string;
  name: string;
  region: string;
  emoji: string;
  lat: number;
  lon: number;
  apiLat: number;
  apiLon: number;
  shelterFactor: number;
  swellWindow: [number, number];
  aspect: number;
  // explore extras
  level?: string;
  tags?: string[];
  desc?: string;
  bestSeason?: string;
  waveType?: string;
  // spot/[id] extras
  photo?: string;
}

export interface SpotRegion {
  id: string;
  label: string;
  spots: SpotData[];
}

// ─── Beach photo pool (Unsplash) ─────────────────────────────────────────────
const PHOTO_BEACH  = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80";
const PHOTO_SURF   = "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=900&q=80";
const PHOTO_WAVE   = "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=900&q=80";
const PHOTO_SHORE  = "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=900&q=80";
const PHOTO_SUNSET = "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=900&q=80";
const PHOTO_JEJU   = "https://images.unsplash.com/photo-1602940659805-770d1b3b9911?w=900&q=80";
const PHOTO_EAST   = "https://images.unsplash.com/photo-1530053969600-caed2596d242?w=900&q=80";

// ─── Raw spot definitions ─────────────────────────────────────────────────────
const RAW_SPOTS: SpotData[] = [
  // ── 부산 ─────────────────────────────────────────────────────────────────
  {
    id: "songjeong",
    name: "송정 해수욕장",
    region: "부산 해운대구",
    emoji: "🐚",
    lat: 35.1786, lon: 129.2075,
    apiLat: 35.1718, apiLon: 129.2218,
    shelterFactor: 0.95,
    swellWindow: [55, 205],
    aspect: 120,
    level: "초중급",
    tags: ["도심 접근성", "일몰 뷰", "초보 가능"],
    desc: "부산 도심에서 가장 가까운 서핑 스팟. 지하철·버스로 접근이 쉽고, 파도가 비교적 완만해 입문자도 즐길 수 있다. 해 질 무렵 오렌지빛 노을이 일품.",
    bestSeason: "연중 (9~11월 최고)",
    waveType: "비치 브레이크",
    photo: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80",
  },
  {
    id: "haeundae",
    name: "해운대 해수욕장",
    region: "부산 해운대구",
    emoji: "🏖️",
    lat: 35.1588, lon: 129.1604,
    apiLat: 35.1466, apiLon: 129.1674,
    shelterFactor: 0.80,
    swellWindow: [100, 220],
    aspect: 155,
    level: "중급",
    tags: ["관광지", "파도 다양", "가끔 대박"],
    desc: "부산 최대 해수욕장. 스웰이 맞으면 훌륭한 파도가 들어온다. 혼잡한 시즌을 피해 이른 아침 세션을 노릴 것.",
    bestSeason: "9~11월 (스웰 시즌)",
    waveType: "비치 브레이크",
    photo: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=900&q=80",
  },
  {
    id: "dadaepo",
    name: "다대포 해수욕장",
    region: "부산 사하구",
    emoji: "🌊",
    lat: 35.0476, lon: 128.9610,
    apiLat: 35.0365, apiLon: 128.9515,
    shelterFactor: 0.75,
    swellWindow: [155, 270],
    aspect: 215,
    level: "초급",
    tags: ["초보 추천", "넓은 백사장", "낙조 명소"],
    desc: "부산 서쪽 끝에 위치한 광활한 해변. 파도가 완만하고 수심이 얕아 입문자에게 최적이다. 낙조 명소로 유명하며 가족 단위 서퍼에게 인기.",
    bestSeason: "5~10월",
    waveType: "비치 브레이크",
    photo: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=900&q=80",
  },
  {
    id: "gwanganri",
    name: "광안리 해수욕장",
    region: "부산 수영구",
    emoji: "🌉",
    lat: 35.1530, lon: 129.1185,
    apiLat: 35.1395, apiLon: 129.1185,
    shelterFactor: 0.35,
    swellWindow: [145, 215],
    aspect: 180,
    level: "SUP 특화",
    tags: ["SUP 성지", "광안대교 뷰", "야간 세션"],
    desc: "부산 SUP의 성지. 수영만 내만 특성상 SUP과 요가에 최적이며, 광안대교를 배경으로 하는 세션은 그 자체로 인생샷.",
    bestSeason: "연중 (봄~가을 추천)",
    waveType: "내만 잔파",
    photo: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=900&q=80",
  },

  // ── 강원 양양군 ──────────────────────────────────────────────────────────
  {
    id: "jukdo",
    name: "죽도 해변",
    region: "강원 양양군",
    emoji: "🏄",
    lat: 38.0836, lon: 128.6337,
    apiLat: 38.0900, apiLon: 128.7200,
    shelterFactor: 0.90,
    swellWindow: [10, 170],
    aspect: 90,
    level: "중급",
    tags: ["양양 대표", "스웰 직격", "서퍼 성지"],
    desc: "양양 최고의 서핑 명소로 꼽히는 스팟. 동해 스웰이 직접 들어와 파도 퀄리티가 높다. 주변에 서프샵과 숙소가 즐비하다.",
    bestSeason: "9~11월",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "inggu",
    name: "인구 해변",
    region: "강원 양양군",
    emoji: "🌊",
    lat: 38.1074, lon: 128.6356,
    apiLat: 38.1100, apiLon: 128.7200,
    shelterFactor: 0.88,
    swellWindow: [10, 170],
    aspect: 90,
    level: "초중급",
    tags: ["아늑한 해변", "초보 가능", "깨끗한 물"],
    desc: "작고 아늑한 해변으로 초보 서퍼에게 인기. 파도가 완만하고 물이 맑다.",
    bestSeason: "여름~가을",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "gisamun",
    name: "기사문 해변",
    region: "강원 양양군",
    emoji: "🗿",
    lat: 38.1203, lon: 128.6382,
    apiLat: 38.1200, apiLon: 128.7200,
    shelterFactor: 0.87,
    swellWindow: [10, 170],
    aspect: 88,
    level: "초중급",
    tags: ["한적한 스팟", "로컬 분위기"],
    desc: "비교적 한적하고 로컬 분위기가 강한 스팟. 조용히 세션을 즐기고 싶은 서퍼에게 추천.",
    bestSeason: "9~11월",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "gaetmaul",
    name: "갯마을 해변",
    region: "강원 양양군",
    emoji: "🏕️",
    lat: 38.0697, lon: 128.6308,
    apiLat: 38.0700, apiLon: 128.7200,
    shelterFactor: 0.88,
    swellWindow: [10, 170],
    aspect: 90,
    level: "초급",
    tags: ["캠핑 가능", "가족 추천", "완만한 파도"],
    desc: "캠핑장이 인접해 있어 캠핑과 서핑을 함께 즐길 수 있는 스팟. 파도가 완만해 초보자에게도 적합.",
    bestSeason: "여름",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "namae3ri",
    name: "남애3리 해변",
    region: "강원 양양군",
    emoji: "🎣",
    lat: 38.0164, lon: 128.6362,
    apiLat: 38.0200, apiLon: 128.7200,
    shelterFactor: 0.88,
    swellWindow: [10, 170],
    aspect: 92,
    level: "중급",
    tags: ["파도 좋음", "로컬 스팟"],
    desc: "로컬 서퍼들이 사랑하는 조용한 스팟. 시즌에는 좋은 파도가 꾸준히 들어온다.",
    bestSeason: "9~11월",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "mulchi",
    name: "물치 해변",
    region: "강원 양양군",
    emoji: "🌾",
    lat: 38.1797, lon: 128.5958,
    apiLat: 38.1800, apiLon: 128.7200,
    shelterFactor: 0.87,
    swellWindow: [10, 170],
    aspect: 85,
    level: "초중급",
    tags: ["접근성 좋음", "알려지지 않은 스팟"],
    desc: "속초 근처의 한적한 스팟. 아직 많이 알려지지 않아 혼잡하지 않다.",
    bestSeason: "가을",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "seorak",
    name: "설악 해변",
    region: "강원 양양군",
    emoji: "⛰️",
    lat: 38.1942, lon: 128.5783,
    apiLat: 38.1900, apiLon: 128.7200,
    shelterFactor: 0.87,
    swellWindow: [10, 170],
    aspect: 80,
    level: "초중급",
    tags: ["설악산 뷰", "경치 최고", "서핑+관광"],
    desc: "설악산을 배경으로 서핑을 즐길 수 있는 특별한 스팟. 경치가 매우 아름답다.",
    bestSeason: "9~10월",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "dongsan",
    name: "동산 해변",
    region: "강원 양양군",
    emoji: "🌿",
    lat: 38.0836, lon: 128.6297,
    apiLat: 38.0800, apiLon: 128.7200,
    shelterFactor: 0.88,
    swellWindow: [10, 170],
    aspect: 90,
    level: "초중급",
    tags: ["죽도 인근", "조용한 분위기"],
    desc: "죽도 해변 인근의 조용한 스팟. 죽도가 혼잡할 때 대안으로 추천.",
    bestSeason: "9~11월",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "surferbeach",
    name: "서퍼비치",
    region: "강원 양양군",
    emoji: "🏄",
    lat: 38.0617, lon: 128.6336,
    apiLat: 38.0600, apiLon: 128.7200,
    shelterFactor: 0.90,
    swellWindow: [10, 170],
    aspect: 90,
    level: "초중급",
    tags: ["서퍼 전용 해변", "서프샵 밀집", "입문자 환영"],
    desc: "이름처럼 서퍼를 위한 해변. 서프샵과 서핑 스쿨이 밀집해 있어 장비 렌탈과 레슨이 편리하다.",
    bestSeason: "여름~가을",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "hajodae",
    name: "하조대 해변",
    region: "강원 양양군",
    emoji: "🪨",
    lat: 38.0419, lon: 128.6386,
    apiLat: 38.0400, apiLon: 128.7200,
    shelterFactor: 0.87,
    swellWindow: [10, 170],
    aspect: 92,
    level: "중급",
    tags: ["하조대 등대", "바위 지형", "경치 좋음"],
    desc: "하조대 등대로 유명한 해변. 주변의 바위 지형이 독특한 분위기를 만들어낸다.",
    bestSeason: "9~11월",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "dongho",
    name: "동호 해변",
    region: "강원 양양군",
    emoji: "🏕️",
    lat: 38.1333, lon: 128.6308,
    apiLat: 38.1300, apiLon: 128.7200,
    shelterFactor: 0.88,
    swellWindow: [10, 170],
    aspect: 90,
    level: "초중급",
    tags: ["캠핑 인기", "조용한 해변"],
    desc: "캠핑 명소로도 알려진 해변. 서핑과 캠핑을 함께 즐길 수 있어 2030에게 인기.",
    bestSeason: "여름~가을",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "naksan",
    name: "낙산 해변",
    region: "강원 양양군",
    emoji: "⛩️",
    lat: 38.1672, lon: 128.6025,
    apiLat: 38.1700, apiLon: 128.7200,
    shelterFactor: 0.86,
    swellWindow: [10, 170],
    aspect: 85,
    level: "초중급",
    tags: ["낙산사 인근", "역사 관광", "서핑+힐링"],
    desc: "낙산사 인근의 해변. 서핑 후 낙산사를 방문하는 코스가 인기다.",
    bestSeason: "여름~가을",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "jeongam",
    name: "정암 해변",
    region: "강원 양양군",
    emoji: "🔮",
    lat: 38.0000, lon: 128.6358,
    apiLat: 38.0000, apiLon: 128.7200,
    shelterFactor: 0.88,
    swellWindow: [10, 170],
    aspect: 90,
    level: "초중급",
    tags: ["한적한 스팟", "로컬 추천"],
    desc: "양양 남쪽의 한적한 해변. 로컬 서퍼들이 즐겨 찾는 숨은 명소.",
    bestSeason: "9~11월",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },

  // ── 강원 고성군 ──────────────────────────────────────────────────────────
  {
    id: "songjho",
    name: "송지호 해변",
    region: "강원 고성군",
    emoji: "🦢",
    lat: 38.3972, lon: 128.5803,
    apiLat: 38.4000, apiLon: 128.7200,
    shelterFactor: 0.88,
    swellWindow: [10, 170],
    aspect: 90,
    level: "초중급",
    tags: ["고성 대표", "석호 인접", "경치 좋음"],
    desc: "고성의 대표 서핑 스팟. 인근 송지호 석호와 어우러진 경치가 아름답다.",
    bestSeason: "9~11월",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "cheonjin",
    name: "천진 해변",
    region: "강원 고성군",
    emoji: "💧",
    lat: 38.3525, lon: 128.5783,
    apiLat: 38.3500, apiLon: 128.7200,
    shelterFactor: 0.88,
    swellWindow: [10, 170],
    aspect: 90,
    level: "초중급",
    tags: ["청정 해변", "수질 좋음"],
    desc: "깨끗하고 맑은 물로 유명한 고성의 해변. 동해 최북단에 위치해 수질이 특히 청정하다.",
    bestSeason: "여름~가을",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },

  // ── 강원 속초시 ──────────────────────────────────────────────────────────
  {
    id: "sokcho",
    name: "속초 해변",
    region: "강원 속초시",
    emoji: "🦞",
    lat: 38.2083, lon: 128.5878,
    apiLat: 38.2100, apiLon: 128.7200,
    shelterFactor: 0.78,
    swellWindow: [10, 170],
    aspect: 85,
    level: "초중급",
    tags: ["속초 시내", "접근성 최고", "관광+서핑"],
    desc: "속초 시내에서 가장 가까운 해변. 속초 관광과 함께 서핑을 즐기기 좋다. 주변에 맛집이 많다.",
    bestSeason: "여름~가을",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },

  // ── 강원 강릉시 ──────────────────────────────────────────────────────────
  {
    id: "geumjin",
    name: "금진 해변",
    region: "강원 강릉시",
    emoji: "🌲",
    lat: 37.6697, lon: 129.0447,
    apiLat: 37.6700, apiLon: 129.1500,
    shelterFactor: 0.85,
    swellWindow: [10, 170],
    aspect: 90,
    level: "중급",
    tags: ["강릉 서핑", "파워풀 파도", "상급자 추천"],
    desc: "강릉의 대표 서핑 스팟 중 하나. 동해 스웰이 직격으로 들어와 파워풀한 파도를 즐길 수 있다.",
    bestSeason: "9~11월",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },
  {
    id: "gyeongpo",
    name: "경포 해변",
    region: "강원 강릉시",
    emoji: "🏊",
    lat: 37.8036, lon: 128.9050,
    apiLat: 37.8000, apiLon: 129.0500,
    shelterFactor: 0.80,
    swellWindow: [10, 170],
    aspect: 85,
    level: "초중급",
    tags: ["경포대 뷰", "강릉 관광", "넓은 해변"],
    desc: "강릉 최대 해변으로 경포대가 인접. 넓은 모래사장과 완만한 파도로 초보자도 즐길 수 있다.",
    bestSeason: "여름~가을",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },

  // ── 강원 동해시 ──────────────────────────────────────────────────────────
  {
    id: "daejin",
    name: "대진 해변",
    region: "강원 동해시",
    emoji: "⚓",
    lat: 37.5167, lon: 129.1167,
    apiLat: 37.5200, apiLon: 129.2500,
    shelterFactor: 0.85,
    swellWindow: [10, 170],
    aspect: 90,
    level: "초중급",
    tags: ["동해시", "한적한 스팟"],
    desc: "동해시의 한적한 서핑 스팟. 혼잡하지 않아 여유로운 세션을 즐길 수 있다.",
    bestSeason: "9~11월",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },

  // ── 강원 삼척시 ──────────────────────────────────────────────────────────
  {
    id: "yonghwa",
    name: "용화 해변",
    region: "강원 삼척시",
    emoji: "🐉",
    lat: 37.4500, lon: 129.1667,
    apiLat: 37.4500, apiLon: 129.2500,
    shelterFactor: 0.85,
    swellWindow: [10, 170],
    aspect: 90,
    level: "초중급",
    tags: ["삼척 숨은 명소", "깨끗한 물"],
    desc: "삼척의 숨은 서핑 명소. 접근성이 다소 떨어지지만 그만큼 한적하고 물이 깨끗하다.",
    bestSeason: "9~11월",
    waveType: "비치 브레이크",
    photo: PHOTO_EAST,
  },

  // ── 제주 ─────────────────────────────────────────────────────────────────
  {
    id: "jungmun",
    name: "중문 해변",
    region: "제주 서귀포시",
    emoji: "🌺",
    lat: 33.2439, lon: 126.4128,
    apiLat: 33.2000, apiLon: 126.4000,
    shelterFactor: 0.80,
    swellWindow: [150, 270],
    aspect: 205,
    level: "중급",
    tags: ["제주 최고", "강한 파도", "상급자 도전"],
    desc: "제주 최고의 서핑 스팟. 남방파도의 영향을 직접 받아 파워풀한 파도가 형성된다. 상급자들이 즐겨 찾는다.",
    bestSeason: "9~2월 (태풍 시즌 포함)",
    waveType: "비치 브레이크",
    photo: PHOTO_JEJU,
  },
  {
    id: "ihoteu",
    name: "이호테우 해변",
    region: "제주시",
    emoji: "🐴",
    lat: 33.5014, lon: 126.4494,
    apiLat: 33.5000, apiLon: 126.3500,
    shelterFactor: 0.35,
    swellWindow: [260, 360],
    aspect: 310,
    level: "초급",
    tags: ["말 등대", "입문자 추천", "제주 북부"],
    desc: "형형색색 말 등대로 유명한 이호테우 해변. 서쪽 스웰을 받아 파도가 부드럽고 완만해 입문자 서핑에 적합하다.",
    bestSeason: "봄~가을",
    waveType: "비치 브레이크",
    photo: PHOTO_JEJU,
  },
  {
    id: "woljeong",
    name: "월정 해변",
    region: "제주시 구좌읍",
    emoji: "💎",
    lat: 33.5669, lon: 126.8183,
    apiLat: 33.6000, apiLon: 126.9000,
    shelterFactor: 0.80,
    swellWindow: [0, 160],
    aspect: 55,
    level: "초중급",
    tags: ["에메랄드 바다", "인스타 명소", "투명한 물"],
    desc: "제주에서 가장 아름다운 에메랄드빛 바다로 유명. 투명한 물과 하얀 모래가 어우러진 절경 속에서 서핑을 즐길 수 있다.",
    bestSeason: "여름~가을",
    waveType: "비치 브레이크",
    photo: PHOTO_JEJU,
  },
  {
    id: "gwakji",
    name: "곽지 해변",
    region: "제주시 애월읍",
    emoji: "🌅",
    lat: 33.4664, lon: 126.3667,
    apiLat: 33.5000, apiLon: 126.2500,
    shelterFactor: 0.60,
    swellWindow: [290, 90],
    aspect: 355,
    level: "초중급",
    tags: ["애월 인근", "용천수 해변", "제주 서부"],
    desc: "제주 서부 애월 인근의 해변. 용천수가 유명하며 제주 서쪽 스웰을 받아 파도가 꾸준하다.",
    bestSeason: "여름~가을",
    waveType: "비치 브레이크",
    photo: PHOTO_JEJU,
  },

  // ── 경북 영덕군 ──────────────────────────────────────────────────────────
  {
    id: "boheung",
    name: "부흥 해변",
    region: "경북 영덕군",
    emoji: "🐟",
    lat: 36.5000, lon: 129.3833,
    apiLat: 36.5000, apiLon: 129.5000,
    shelterFactor: 0.85,
    swellWindow: [10, 170],
    aspect: 90,
    level: "초중급",
    tags: ["영덕 서핑", "한적한 스팟"],
    desc: "영덕의 조용한 서핑 스팟. 혼잡하지 않아 여유로운 세션을 즐길 수 있다.",
    bestSeason: "9~11월",
    waveType: "비치 브레이크",
    photo: PHOTO_BEACH,
  },
  {
    id: "sinhangman",
    name: "신항만 해변",
    region: "경북 영덕군",
    emoji: "⚓",
    lat: 36.4500, lon: 129.3833,
    apiLat: 36.4500, apiLon: 129.5000,
    shelterFactor: 0.85,
    swellWindow: [10, 170],
    aspect: 90,
    level: "초중급",
    tags: ["항구 인근", "파도 안정적"],
    desc: "신항만 인근의 서핑 스팟. 항구의 영향으로 파도가 비교적 안정적이다.",
    bestSeason: "9~11월",
    waveType: "비치 브레이크",
    photo: PHOTO_BEACH,
  },

  // ── 경북 포항시 ──────────────────────────────────────────────────────────
  {
    id: "wolpo",
    name: "월포 해변",
    region: "경북 포항시",
    emoji: "🌙",
    lat: 36.1500, lon: 129.3833,
    apiLat: 36.1500, apiLon: 129.5000,
    shelterFactor: 0.82,
    swellWindow: [10, 170],
    aspect: 90,
    level: "초중급",
    tags: ["포항 서핑", "깨끗한 물", "모래 바닥"],
    desc: "포항 북부의 서핑 스팟. 깨끗한 모래 바닥과 안정적인 파도로 인기를 얻고 있다.",
    bestSeason: "9~11월",
    waveType: "비치 브레이크",
    photo: PHOTO_BEACH,
  },

  // ── 충남 태안군 (서해) ───────────────────────────────────────────────────
  {
    id: "malliopo",
    name: "만리포 해변",
    region: "충남 태안군",
    emoji: "🌅",
    lat: 36.8331, lon: 126.1497,
    apiLat: 36.8500, apiLon: 125.9000,
    shelterFactor: 0.38,
    swellWindow: [230, 350],
    aspect: 290,
    level: "초중급",
    tags: ["서해 서핑", "일몰 명소", "태안 국립공원"],
    desc: "서해안 최고의 서핑 스팟. 태안해안국립공원 내에 위치하며 서쪽 스웰을 받아 파도가 꾸준하다. 일몰 경치가 절경이다.",
    bestSeason: "9~11월 (북서풍 시즌)",
    waveType: "비치 브레이크",
    photo: PHOTO_SUNSET,
  },
];

// ─── Regional groupings ───────────────────────────────────────────────────────
export const SPOT_REGIONS: SpotRegion[] = [
  {
    id: "busan",
    label: "부산",
    spots: RAW_SPOTS.filter(s => s.region.startsWith("부산")),
  },
  {
    id: "yangyang",
    label: "강원 양양",
    spots: RAW_SPOTS.filter(s => s.region === "강원 양양군"),
  },
  {
    id: "goseong",
    label: "강원 고성",
    spots: RAW_SPOTS.filter(s => s.region === "강원 고성군"),
  },
  {
    id: "sokcho",
    label: "강원 속초",
    spots: RAW_SPOTS.filter(s => s.region === "강원 속초시"),
  },
  {
    id: "gangneung",
    label: "강원 강릉",
    spots: RAW_SPOTS.filter(s => s.region === "강원 강릉시"),
  },
  {
    id: "donghae",
    label: "강원 동해",
    spots: RAW_SPOTS.filter(s => s.region === "강원 동해시"),
  },
  {
    id: "samcheok",
    label: "강원 삼척",
    spots: RAW_SPOTS.filter(s => s.region === "강원 삼척시"),
  },
  {
    id: "jeju",
    label: "제주",
    spots: RAW_SPOTS.filter(s => s.region.startsWith("제주")),
  },
  {
    id: "yeongdeok",
    label: "경북 영덕",
    spots: RAW_SPOTS.filter(s => s.region === "경북 영덕군"),
  },
  {
    id: "pohang",
    label: "경북 포항",
    spots: RAW_SPOTS.filter(s => s.region === "경북 포항시"),
  },
  {
    id: "seohae",
    label: "서해 (태안)",
    spots: RAW_SPOTS.filter(s => s.region === "충남 태안군"),
  },
];

/** Flat array of all spots */
export const ALL_SPOTS_FLAT: SpotData[] = RAW_SPOTS;

// ─── 2단계 지역 그룹 (통합 탭 → 세부 탭) ─────────────────────────────────────
export interface RegionGroup {
  id: string;
  label: string;
  /** SPOT_REGIONS id 목록 (하나면 세부 탭 없이 바로 스팟 표시) */
  subIds: string[];
}

export const REGION_GROUPS: RegionGroup[] = [
  { id: "busan",   label: "부산",  subIds: ["busan"] },
  {
    id: "gangwon", label: "강원도", subIds: ["yangyang", "goseong", "sokcho", "gangneung", "donghae", "samcheok"],
  },
  { id: "jeju",    label: "제주",  subIds: ["jeju"] },
  { id: "gyeongbuk", label: "경북", subIds: ["yeongdeok", "pohang"] },
  { id: "seohae",  label: "서해",  subIds: ["seohae"] },
];

/** Record lookup by spot ID */
export const SPOT_BY_ID: Record<string, SpotData> = Object.fromEntries(
  RAW_SPOTS.map(s => [s.id, s])
);
